# Generated by Django 3.0.7 on 2020-10-05 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20201004_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Модель')),
                ('V', models.SmallIntegerField(verbose_name='Выходное напряжение')),
                ('I', models.SmallIntegerField(verbose_name='Сила тока')),
                ('appointment', models.CharField(max_length=150, verbose_name='Назначение')),
                ('size', models.CharField(max_length=150, verbose_name='Размер')),
                ('term', models.SmallIntegerField(verbose_name='Срок работы')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='projectModels',
            field=models.ManyToManyField(null=True, to='projects.ProjectModel', verbose_name='Модели'),
        ),
    ]
