# Generated by Django 3.0.7 on 2020-10-05 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20201005_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='V',
            field=models.FloatField(verbose_name='Выходное напряжение'),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='term',
            field=models.FloatField(verbose_name='Срок работы'),
        ),
    ]
