# Generated by Django 3.0.7 on 2020-10-05 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20201005_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='I',
            field=models.FloatField(verbose_name='Сила тока'),
        ),
    ]
