# Generated by Django 3.0.7 on 2020-10-08 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forPartners', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'Документ', 'verbose_name_plural': 'Документы'},
        ),
        migrations.AlterModelOptions(
            name='info',
            options={'verbose_name': 'Инфоблок', 'verbose_name_plural': 'Инфоблоки'},
        ),
    ]
