# Generated by Django 3.0.7 on 2020-10-09 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forPartners', '0002_auto_20201008_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='filename',
            field=models.CharField(default=models.CharField(max_length=150, verbose_name='Название документа'), max_length=150, verbose_name='Имя файла'),
        ),
    ]
