# Generated by Django 3.0.7 on 2020-10-09 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forPartners', '0003_document_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='filename',
            field=models.CharField(default='<django.db.models.fields.CharField>', max_length=150, verbose_name='Имя файла'),
        ),
    ]
