# Generated by Django 3.0.7 on 2020-10-09 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forPartners', '0006_document_public'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='file',
            new_name='<django.db.models.fields.CharField>',
        ),
    ]
