# Generated by Django 3.0.7 on 2020-10-09 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forPartners', '0007_auto_20201009_2045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='<django.db.models.fields.CharField>',
            new_name='file',
        ),
    ]
