# Generated by Django 3.0.7 on 2020-10-11 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forPartners', '0008_auto_20201009_2046'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50, verbose_name='Имя')),
                ('lastName', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('companyName', models.CharField(max_length=150, verbose_name='Название организации')),
                ('Email', models.EmailField(max_length=254, verbose_name='Email')),
                ('message', models.CharField(max_length=1000, verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Партнёр',
                'verbose_name_plural': 'Партнёры',
            },
        ),
    ]
