# Generated by Django 3.0.7 on 2020-10-15 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forPartners', '0009_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='message',
            field=models.TextField(verbose_name='Сообщение'),
        ),
    ]
