# Generated by Django 3.0.7 on 2020-10-04 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_auto_20201002_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='check',
            field=models.BooleanField(default=False, verbose_name='В проверке/Проверено'),
        ),
    ]
