# Generated by Django 3.0.7 on 2020-10-04 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_auto_20201004_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='Email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Почта спросившего'),
        ),
        migrations.AlterField(
            model_name='question',
            name='name',
            field=models.CharField(blank=True, default='Incognito', max_length=150, null=True, verbose_name='Имя спросившего'),
        ),
    ]
