# Generated by Django 3.0.7 on 2020-10-05 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryGalleryPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='storyGalleryPhotos', verbose_name='Фото')),
                ('name', models.CharField(default='', max_length=100, null=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фото',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50, verbose_name='Имя')),
                ('lastName', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('position', models.CharField(max_length=150, verbose_name='Должность')),
                ('about', models.TextField(verbose_name='О человеке (вкратце)')),
                ('yearOfAccesion', models.SmallIntegerField(verbose_name='В каком году пришёл')),
                ('photo', models.ImageField(upload_to='team', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Член команды',
                'verbose_name_plural': 'Члены команды',
            },
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'verbose_name': 'Партнёр', 'verbose_name_plural': 'Партнёры'},
        ),
        migrations.AlterModelOptions(
            name='story',
            options={'verbose_name': 'Событие', 'verbose_name_plural': 'События'},
        ),
        migrations.AddField(
            model_name='partner',
            name='logo',
            field=models.ImageField(null=True, upload_to='partners', verbose_name='Логотип'),
        ),
        migrations.AddField(
            model_name='partner',
            name='name',
            field=models.CharField(default='', max_length=150, verbose_name='Компания'),
        ),
        migrations.AddField(
            model_name='story',
            name='description',
            field=models.TextField(default='', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='story',
            name='photo',
            field=models.ImageField(null=True, upload_to='storyPhotos', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='story',
            name='title',
            field=models.CharField(default='', max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='story',
            name='video',
            field=models.FileField(null=True, upload_to='', verbose_name='Видео'),
        ),
        migrations.AddField(
            model_name='story',
            name='gallery',
            field=models.ManyToManyField(null=True, to='about.StoryGalleryPhoto', verbose_name='Галлерея'),
        ),
    ]
