# Generated by Django 3.0.7 on 2020-10-05 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_partnergroup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PartnerGroup',
        ),
    ]
