# Generated by Django 3.0.7 on 2020-10-15 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_delete_partnergroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='phoneNumber',
            field=models.CharField(default=None, max_length=13, null=True, verbose_name='Телефон'),
        ),
    ]
