# Generated by Django 3.0.7 on 2020-10-15 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_auto_20201015_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='number',
            field=models.CharField(max_length=17, verbose_name='Номер'),
        ),
    ]
